### ISSUE TITLE
incompatible with ibis 1.4.0

### ISSUE THREAD

**Issue by tswast** [ibis-project/ibis-bigquery#28]
```
      1 import ibis
----> 2 import ibis_bigquery
      3
      4 conn = ibis_bigquery.Backend().connect(
      5     project_id=YOUR_PROJECT_ID,

/usr/local/Caskroom/miniconda/base/envs/scratch/lib/python3.9/site-packages/ibis_bigquery/__init__.py in <module>
      7 import ibis.config
      8 import pydata_google_auth
----> 9 from ibis.backends.base import BaseBackend
     10 from pydata_google_auth import cache
     11

ModuleNotFoundError: No module named 'ibis.backends.base'
```

As we go through this transitional state, it might be useful in helping people upgrade if the backend were compatible across the 1.x / 2.x divide. (I'm thinking of `pandas-gbq`, which can be used directly with older versions of pandas, even if we expect most people to use it via `pandas.read_gbq`)

I'm also motivated to get this package out for 1.x users, as I was able to fix the UDFs implementation on Python 3.8+ in https://github.com/ibis-project/ibis-bigquery/issues/6

CC @datapythonista In case you have thoughts about 1.x compatibility during the 2.x refactor.

**Comment by datapythonista** [comment]
My plan was to simply make backends after Ibis 2.0 only compatible with Ibis >= 2.0. Until now, the bigquery backend for 1.3 was only compatible with Ibis 1.3 since they were coming together I guess. Not sure if was possible with pip to have different versions, I don't think that was intended.

If you make ibis-bigquery 2.0 (or whatever is the first version) compatible with Ibis 1.4, you'll have the two versions installed, at least when installing with conda-forge, since Ibis 1.4 included a bigquery backend.

Since Ibis 2.0 will be mostly 1.4 with the system to support third-party backends better I don't see an important use case to support it anyway.

So, personally I'd just require ibis>=2.0, and explicitly not let users install this package with older Ibis versions.

**Comment by tswast** [comment]
Thanks for the perspective. I think I'll try and see if I can make it compatible with 1.4. Otherwise, fine waiting for 2.0. It'd just be nice to get ahead of it and avoid synchronization problems.

**Comment by tswast** [comment]
Fixec by https://github.com/ibis-project/ibis-bigquery/pull/31
